[phases.setup]
nixPkgs = ["dotnet-sdk_8"]  # stable .NET 8

[phases.build]
commands = [
  "cd Server && dotnet restore",
  "cd Server && dotnet publish -c Release -o out"
]

[phases.start]
cmd = "dotnet Server/out/Server.dll"